/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as DeploymentSuccessRouteImport } from './routes/deployment-success'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditProjectNameRouteImport } from './routes/edit.$projectName'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentSuccessRoute = DeploymentSuccessRouteImport.update({
  id: '/deployment-success',
  path: '/deployment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProjectNameRoute = EditProjectNameRouteImport.update({
  id: '/edit/$projectName',
  path: '/edit/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deployment-success': typeof DeploymentSuccessRoute
  '/test': typeof TestRoute
  '/edit/$projectName': typeof EditProjectNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deployment-success': typeof DeploymentSuccessRoute
  '/test': typeof TestRoute
  '/edit/$projectName': typeof EditProjectNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deployment-success': typeof DeploymentSuccessRoute
  '/test': typeof TestRoute
  '/edit/$projectName': typeof EditProjectNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/deployment-success'
    | '/test'
    | '/edit/$projectName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/deployment-success'
    | '/test'
    | '/edit/$projectName'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/deployment-success'
    | '/test'
    | '/edit/$projectName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DeploymentSuccessRoute: typeof DeploymentSuccessRoute
  TestRoute: typeof TestRoute
  EditProjectNameRoute: typeof EditProjectNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment-success': {
      id: '/deployment-success'
      path: '/deployment-success'
      fullPath: '/deployment-success'
      preLoaderRoute: typeof DeploymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$projectName': {
      id: '/edit/$projectName'
      path: '/edit/$projectName'
      fullPath: '/edit/$projectName'
      preLoaderRoute: typeof EditProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DeploymentSuccessRoute: DeploymentSuccessRoute,
  TestRoute: TestRoute,
  EditProjectNameRoute: EditProjectNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
