// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the templates plugin.
// To add a new template, run 'pnpm create-template "Template Name"'
// and export a 'name' const. The plugin will automatically regenerate this file.

import CoolestTemplate from "../templates/coolest";
import MinimalTemplate from "../templates/minimal-template";
import ModernTemplate from "../templates/modern-template";
import ProfessionalTemplate from "../templates/professional-template";

const templates = {
	coolest: { name: "coolest", component: CoolestTemplate },
	minimal: { name: "Minimal", component: MinimalTemplate },
	modern: { name: "Modern", component: ModernTemplate },
	professional: { name: "Professional", component: ProfessionalTemplate },
} as const;

export type TemplateType = keyof typeof templates;
export default templates;
