// 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by generate-template-screenshots.js
// Run 'pnpm generate-screenshots' to regenerate

import coolestTemplatePreview from "./coolest-template.webp";
import minimalTemplatePreview from "./minimal-template.webp";
import modernTemplatePreview from "./modern-template.webp";
import professionalTemplatePreview from "./professional-template.webp";

export const templatePreviews = {
	coolest: coolestTemplatePreview,
	minimal: minimalTemplatePreview,
	modern: modernTemplatePreview,
	professional: professionalTemplatePreview,
} as const;

export type TemplateKey = keyof typeof templatePreviews;

// Individual exports for convenience
export { default as coolestTemplatePreview } from "./coolest-template.webp";
export { default as minimalTemplatePreview } from "./minimal-template.webp";
export { default as modernTemplatePreview } from "./modern-template.webp";
export { default as professionalTemplatePreview } from "./professional-template.webp";
